Vagrant.configure("2") do |config|
  config.vm.define "source" do |source|
    source.vm.provider "docker" do |d|
      d.image = "ubuntu:latest"
      d.create_args = ["-i"]
      d.remains_running = true
      d.post_install_provision "shell", inline: <<-'SHELL'
        sudo apt update
        echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive apt install -y tshark tcpdump
      SHELL
    end

    source.vm.network :private_network, ip: "192.168.2.3", netmask: "24"
  end

  config.vm.define "switch" do |switch|
    switch.vm.provider "docker" do |d|
      d.image = "ubuntu:latest"
      d.create_args = ["-i"]
      d.remains_running = true
      d.post_install_provision "shell", inline: <<-'SHELL'
        sudo apt update
        echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive apt install -y tshark tcpdump
      SHELL
    end

    #     switch.vm.synced_folder "../../build", "/vagrant"     # use `vagrant rsync-auto` in this folder to make it automatically synced
    # switch.bindfs.bind_folder "/whatever", "/vagrant"

    switch.vm.network :private_network, ip: "192.168.2.4", netmask: "24"
    switch.vm.network :private_network, ip: "192.168.3.4", netmask: "24"
  end

  config.vm.define "destination" do |destination|
    destination.vm.provider "docker" do |d|
      d.image = "ubuntu:latest"
      d.create_args = ["-i"]
      d.remains_running = true
      d.post_install_provision "shell", inline: <<-'SHELL'
        sudo apt update
        echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections
        sudo DEBIAN_FRONTEND=noninteractive apt install -y tshark tcpdump
      SHELL
    end

    destination.vm.network :private_network, ip: "192.168.3.3", netmask: "24"
  end
end
